import canonical_symplectic_transformations_problems_hamiltonian_canonical_lane_mathlib.GateLemmas
namespace HautevilleHouse
namespace canonical_symplectic_transformations_problems_hamiltonian_canonical_lane_mathlib
structure ConstrainedTheoremClosure where
  admissible :: intro :: constraint :: consequence :: proof ::
theorem canonical : ConstrainedTheoremClosure :=
  ConstrainedTheoremClosure.intro
end canonical_symplectic_transformations_problems_hamiltonian_canonical_lane_mathlib
end HautevilleHouse
